// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationUnknown-0]
	_ = x[OperationOr-1]
	_ = x[OperationAnd-2]
	_ = x[OperationEqual-3]
	_ = x[OperationNotEqual-4]
	_ = x[OperationLess-5]
	_ = x[OperationGreater-6]
	_ = x[OperationLessEqual-7]
	_ = x[OperationGreaterEqual-8]
	_ = x[OperationPlus-9]
	_ = x[OperationMinus-10]
	_ = x[OperationMul-11]
	_ = x[OperationDiv-12]
	_ = x[OperationMod-13]
	_ = x[OperationNegate-14]
	_ = x[OperationNilCoalesce-15]
	_ = x[OperationCreateRange-16]
	_ = x[OperationMove-17]
	_ = x[OperationCast-18]
	_ = x[OperationFailableCast-19]
	_ = x[OperationForceCast-20]
	_ = x[OperationBitwiseOr-21]
	_ = x[OperationBitwiseXor-22]
	_ = x[OperationBitwiseAnd-23]
	_ = x[OperationBitwiseLeftShift-24]
	_ = x[OperationBitwiseRightShift-25]
}

const _Operation_name = "OperationUnknownOperationOrOperationAndOperationEqualOperationNotEqualOperationLessOperationGreaterOperationLessEqualOperationGreaterEqualOperationPlusOperationMinusOperationMulOperationDivOperationModOperationNegateOperationNilCoalesceOperationCreateRangeOperationMoveOperationCastOperationFailableCastOperationForceCastOperationBitwiseOrOperationBitwiseXorOperationBitwiseAndOperationBitwiseLeftShiftOperationBitwiseRightShift"

var _Operation_index = [...]uint16{0, 16, 27, 39, 53, 70, 83, 99, 117, 138, 151, 165, 177, 189, 201, 216, 236, 256, 269, 282, 303, 321, 339, 358, 377, 402, 428}

func (i Operation) String() string {
	if i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
