// Code generated by "stringer -type=precedence"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[precedenceUnknown-0]
	_ = x[precedenceTernary-1]
	_ = x[precedenceLogicalOr-2]
	_ = x[precedenceLogicalAnd-3]
	_ = x[precedenceComparison-4]
	_ = x[precedenceNilCoalescing-5]
	_ = x[precedenceCreateRange-6]
	_ = x[precedenceBitwiseOr-7]
	_ = x[precedenceBitwiseXor-8]
	_ = x[precedenceBitwiseAnd-9]
	_ = x[precedenceBitwiseShift-10]
	_ = x[precedenceAddition-11]
	_ = x[precedenceMultiplication-12]
	_ = x[precedenceCasting-13]
	_ = x[precedenceUnaryPrefix-14]
	_ = x[precedenceUnaryPostfix-15]
	_ = x[precedenceAccess-16]
	_ = x[precedenceLiteral-17]
}

const _precedence_name = "precedenceUnknownprecedenceTernaryprecedenceLogicalOrprecedenceLogicalAndprecedenceComparisonprecedenceNilCoalescingprecedenceCreateRangeprecedenceBitwiseOrprecedenceBitwiseXorprecedenceBitwiseAndprecedenceBitwiseShiftprecedenceAdditionprecedenceMultiplicationprecedenceCastingprecedenceUnaryPrefixprecedenceUnaryPostfixprecedenceAccessprecedenceLiteral"

var _precedence_index = [...]uint16{0, 17, 34, 53, 73, 93, 116, 137, 156, 176, 196, 218, 236, 260, 277, 298, 320, 336, 353}

func (i precedence) String() string {
	if i >= precedence(len(_precedence_index)-1) {
		return "precedence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _precedence_name[_precedence_index[i]:_precedence_index[i+1]]
}
